// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const getFilm = `-- name: GetFilm :one
SELECT
    id,
    title,
    year,
    runtime,
    synopsis,
    imdb_id,
    poster_url,
    created_at
FROM films
WHERE id = $1
`

func (q *Queries) GetFilm(ctx context.Context, id int64) (Film, error) {
	row := q.db.QueryRow(ctx, getFilm, id)
	var i Film
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Year,
		&i.Runtime,
		&i.Synopsis,
		&i.ImdbID,
		&i.PosterUrl,
		&i.CreatedAt,
	)
	return i, err
}

const insertFilm = `-- name: InsertFilm :one
INSERT INTO films (id, title, year, runtime, synopsis)
SELECT COALESCE(MAX(id), 0) + 1, $1, $2, $3, $4
FROM films
RETURNING id, title, year, runtime, synopsis, imdb_id, poster_url, created_at
`

type InsertFilmParams struct {
	Title    string  `db:"title"`
	Year     *int32  `db:"year"`
	Runtime  *int32  `db:"runtime"`
	Synopsis *string `db:"synopsis"`
}

// Usada por CreateFilm (RF02/task 0002): o subcomando CLI criar-filme insere o
// filme e enfileira catalogo.filme_criado na mesma TX via outbox.Enqueue.
// films.id é BIGINT sem identity/sequence (schema da migration 001); o próximo
// id é calculado por MAX(id)+1 dentro do próprio statement — simplificação
// aceitável para uma ferramenta de operador único (CLI, sem concorrência real);
// colisão eventual é reportada como erro de constraint (exit code != 0 na CLI).
func (q *Queries) InsertFilm(ctx context.Context, arg InsertFilmParams) (Film, error) {
	row := q.db.QueryRow(ctx, insertFilm,
		arg.Title,
		arg.Year,
		arg.Runtime,
		arg.Synopsis,
	)
	var i Film
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Year,
		&i.Runtime,
		&i.Synopsis,
		&i.ImdbID,
		&i.PosterUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listFilms = `-- name: ListFilms :many
SELECT
    id,
    title,
    year,
    runtime,
    synopsis,
    imdb_id,
    poster_url,
    created_at
FROM films
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) ListFilms(ctx context.Context) ([]Film, error) {
	rows, err := q.db.Query(ctx, listFilms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Film
	for rows.Next() {
		var i Film
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Year,
			&i.Runtime,
			&i.Synopsis,
			&i.ImdbID,
			&i.PosterUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
