// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	GetFilm(ctx context.Context, id int64) (Film, error)
	ListFilms(ctx context.Context) ([]Film, error)
}

var _ Querier = (*Queries)(nil)
