// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const getFilm = `-- name: GetFilm :one
SELECT
    id,
    title,
    year,
    runtime,
    synopsis,
    imdb_id,
    poster_url,
    created_at
FROM films
WHERE id = $1
`

func (q *Queries) GetFilm(ctx context.Context, id int64) (Film, error) {
	row := q.db.QueryRow(ctx, getFilm, id)
	var i Film
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Year,
		&i.Runtime,
		&i.Synopsis,
		&i.ImdbID,
		&i.PosterUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listFilms = `-- name: ListFilms :many
SELECT
    id,
    title,
    year,
    runtime,
    synopsis,
    imdb_id,
    poster_url,
    created_at
FROM films
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) ListFilms(ctx context.Context) ([]Film, error) {
	rows, err := q.db.Query(ctx, listFilms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Film
	for rows.Next() {
		var i Film
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Year,
			&i.Runtime,
			&i.Synopsis,
			&i.ImdbID,
			&i.PosterUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
