// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxEvent struct {
	ID          pgtype.UUID        `db:"id"`
	EventType   string             `db:"event_type"`
	AggregateID string             `db:"aggregate_id"`
	OccurredAt  pgtype.Timestamptz `db:"occurred_at"`
	Payload     []byte             `db:"payload"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	PublishedAt pgtype.Timestamptz `db:"published_at"`
}
