// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const contarPendentes = `-- name: ContarPendentes :one
SELECT count(*) FROM outbox_events WHERE published_at IS NULL
`

func (q *Queries) ContarPendentes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, contarPendentes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO outbox_events (event_type, aggregate_id, occurred_at, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, event_type, aggregate_id, occurred_at, payload, created_at, published_at
`

type InsertEventParams struct {
	EventType   string             `db:"event_type"`
	AggregateID string             `db:"aggregate_id"`
	OccurredAt  pgtype.Timestamptz `db:"occurred_at"`
	Payload     []byte             `db:"payload"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.EventType,
		arg.AggregateID,
		arg.OccurredAt,
		arg.Payload,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.AggregateID,
		&i.OccurredAt,
		&i.Payload,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const marcarPublicado = `-- name: MarcarPublicado :exec
UPDATE outbox_events
SET published_at = $2
WHERE id = $1
`

type MarcarPublicadoParams struct {
	ID          pgtype.UUID        `db:"id"`
	PublishedAt pgtype.Timestamptz `db:"published_at"`
}

func (q *Queries) MarcarPublicado(ctx context.Context, arg MarcarPublicadoParams) error {
	_, err := q.db.Exec(ctx, marcarPublicado, arg.ID, arg.PublishedAt)
	return err
}

const selectPendentesParaPublicar = `-- name: SelectPendentesParaPublicar :many
SELECT id, event_type, aggregate_id, occurred_at, payload, created_at, published_at
FROM outbox_events
WHERE published_at IS NULL
ORDER BY created_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// Lote de eventos ainda não publicados, travados para esta transação
// (SKIP LOCKED deixa outras instâncias do relay pularem linhas já em processamento
// em vez de bloquear — RF03/ADR 0007).
func (q *Queries) SelectPendentesParaPublicar(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, selectPendentesParaPublicar, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateID,
			&i.OccurredAt,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
