// Code generated by sqlc. DO NOT EDIT.
// Versions:
//   sqlc v1.25.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"
)

// Film represents a row from the 'films' table
type Film struct {
	ID        int64     `db:"id"`
	Title     string    `db:"title"`
	Year      *int32    `db:"year"`
	Runtime   *int32    `db:"runtime"`
	Synopsis  *string   `db:"synopsis"`
	ImdbID    *string   `db:"imdb_id"`
	PosterUrl *string   `db:"poster_url"`
	CreatedAt time.Time `db:"created_at"`
}

// Value implements the driver.Valuer interface.
func (f Film) Value() (driver.Value, error) {
	return f, nil
}
