// Code generated by sqlc. DO NOT EDIT.
// Versions:
//   sqlc v1.25.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	ListFilms(ctx context.Context) ([]Film, error)
	GetFilm(ctx context.Context, id int64) (Film, error)
}

type Queries struct {
	db DBTX
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func (q *Queries) WithTx(tx pgx.Tx) *Queries {
	return &Queries{
		db: tx,
	}
}

// DBTX is a common interface for *pgx.Conn and *pgx.Tx
type DBTX interface {
	Query(context.Context, string, ...interface{}) (pgx.Rows, error)
	QueryRow(context.Context, string, ...interface{}) pgx.Row
	Exec(context.Context, string, ...interface{}) (pgconn.CommandTag, error)
}

// ListFilms lists all films ordered by creation date
func (q *Queries) ListFilms(ctx context.Context) ([]Film, error) {
	const query = `
SELECT
    id,
    title,
    year,
    runtime,
    synopsis,
    imdb_id,
    poster_url,
    created_at
FROM films
ORDER BY created_at DESC
LIMIT 100`

	rows, err := q.db.Query(ctx, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Film
	for rows.Next() {
		var i Film
		if err := rows.Scan(&i.ID, &i.Title, &i.Year, &i.Runtime, &i.Synopsis, &i.ImdbID, &i.PosterUrl, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// GetFilm retrieves a film by ID
func (q *Queries) GetFilm(ctx context.Context, id int64) (Film, error) {
	const query = `
SELECT
    id,
    title,
    year,
    runtime,
    synopsis,
    imdb_id,
    poster_url,
    created_at
FROM films
WHERE id = $1`

	row := q.db.QueryRow(ctx, query, id)
	var i Film
	err := row.Scan(&i.ID, &i.Title, &i.Year, &i.Runtime, &i.Synopsis, &i.ImdbID, &i.PosterUrl, &i.CreatedAt)
	return i, err
}
